version: "3.8"

services:
  server:
    image: ghcr.io/${GITHUB_REPOSITORY}-server:main
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
